### ISSUE TITLE
v1.3 Checkup 2,3,5 Unable to be identified by UE4

### ISSUE THREAD

**Issue by hahaxiaowai** [CesiumGS/cesium-unreal-samples#12]
I downloaded the TAG package of V1.3, But the documents of the levels 2, 3, 5 cannot be identified by UE4,Then I downloaded V1.1 is normal.

**Comment by kring** [comment]
Are you using Cesium for Unreal v1.3.1 or later?

**Comment by hahaxiaowai** [comment]
all right,I update and it's working,thanks
