### ISSUE TITLE
Update Cesium for Unreal Samples levels to show new features

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal-samples#20]
We need to show off a few more features in the Samples:

- [x] Multiple view frustrums (multiple views rendering tiles at once, possibly using a minimap or something similar)
- [x] Clipping (clipping around Denver tileset)
- [x] Material editing (overlay streets? Custom watermask?)

**Comment by AmeliaWang93** [comment]
I would like to use these new features, especially clipping  and material editing, where I can learn to use them now? Any document？

**Comment by kring** [comment]
@AmeliaWang93 there's a full tutorial coming, but in the meantime Alex's post on the community forum should get you started:
https://community.cesium.com/t/cesium-cartographic-polygon/15128

**Comment by AmeliaWang93** [comment]
@kring  Thanks for your reply！I'll try it soom!
