### ISSUE TITLE
Add material(s) for procedural windows on OSM buildings

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal-samples#36]
A while ago, I was inspired by [this forum post](https://community.cesium.com/t/easiest-way-to-make-a-night-time-scene/17582/2) to make a procedural window material for OSM buildings. After some polish, it works well in most areas and I'd love to make it available for Cesium for Unreal users. This comment contains an overview of the material that I made. We can use this issue to discuss whether it's appropriate to add to the samples, as well as possible improvements, adjustments, or alternatives.

The assets have been added to the branch [procedural-osm-material](https://github.com/CesiumGS/cesium-unreal-samples/tree/procedural-osm-material), and a pull request has been created [here](https://github.com/CesiumGS/cesium-unreal-samples/pull/37). 

## What is this material?
_(There's actually two materials, one that uses metadata for randomization, and one that doesn't, but they are similar otherwise. The metadata version is shown in the initial images.)_
These materials add a window-like effect along the sides of OSM Buildings meshes. It can work with any tileset, but is designed for the simpler OSM buildings rather than photogrammetry. 
![image](https://user-images.githubusercontent.com/39537389/207653204-bb7917a5-ec47-4d30-a788-b08bc6c0fdda.png)

The windows are a darker color, and reflect the environment. They are also emissive, which can create a "city lights" effect in nighttime scenes. 
![image](https://user-images.githubusercontent.com/39537389/207653779-15fd52a6-c214-4a43-9fa5-0e9959df69d2.png)

The materials have adjustable parameters so that users can optimize them for their scenes. For example, you can adjust building colors, window size, emissive intensity, and roughness of both the building and the window. 

The material only maps along the sides of buildings, and even works for slanted roofs. The angle at which it cuts off the windows can be adjusted. 
![image](https://user-images.githubusercontent.com/39537389/207665506-a66e044d-bea4-485b-9584-60be4ee387a1.png)

There's two variants:

- ProceduralWindowsMetadata
   - This version uses a CesiumEncodedMetadata component to randomize building colors based on each primitive's `elementId` parameter. It is a slightly more expensive and complex shader, but produces a more convincing visual effect.
   - This is the material used for the two above pictures.
   - It offers additional customization of night appearance, which can result in varied brightness between buildings or buildings with their lights off.
   - It requires that the CesiumOSMBuildings tileset has a CesiumEncodedMetadata component set to the appropriate Material Layer, with all attributes except `elementId` removed. 
   - It does not appear to be currently compatible with Bing Maps Raster Overlays - Adding an imagery overlay consistently seemed to break the metadata styling. 
- ProceduralWindowsSimple
   - This version does NOT use metadata to influence color, and as a result each building is the same color. It does have all other features mentioned in the overview above.
   - ![image](https://user-images.githubusercontent.com/39537389/207657365-c6f83db9-c723-4321-9f22-9876e46b460e.png)
   - This material can work with a Bing Maps Raster Overlay, which serves to add color variation.
   - ![image](https://user-images.githubusercontent.com/39537389/207659145-e218909e-7fe1-4c32-be13-f250b91ffb1f.png)
   - Implementation note - I haven't been able to find a convincing solution for color variation for this version. Typical techniques that use noise to influence object color don't work in this case, because it's a 3D tileset. The actor itself can't recognize one building from another without using metadata. 2D or 3D noise textures are an option, but because it must be applied in world space, you will have clusters of buildings of the same color, and some buildings will be multicolored in a very non-building way.

These materials could be expanded upon for improved visual fidelity. For example, instead of blending between different colors, you could use metadata to choose between textures, like brick or stone. 

## Performance 
These materials perform within the typical range for 3D Tileset materials. Neither significantly impacted FPS on my machine. 
They both use a 1024x1024 texture, which introduces some overhead. 
![WindowAlpha_128](https://user-images.githubusercontent.com/39537389/207661778-9231f7eb-6c5a-41b2-b3e5-02a8f7d76286.png)

ProceduralWindowsSimple stats:

- Base pass shader: 201 instructions
- Base pass shader with Volumetric Lightmap: 289 instructions
- Base Pass vertex shader: 71 instructions
- Texture samplers: 8 (9 if using Bing Maps imagery)

ProceduralWindowsMetadata stats:

- Base pass shader: 242 instructions
- Base pass shader with Volumetric Lightmap: 329 instructions
- Base Pass vertex shader: 71 instructions
- Texture samplers: 8 

To compare, here are the stats for MI_CesiumThreeOverlaysAndClipping, which is the default Cesium for Unreal material.
- Base pass shader: 237 instructions
- Base pass shader with Volumetric Lightmap: 325 instructions
- Base Pass vertex shader: 71 instructions
- Texture samplers: 12 

## Caveats
Note that this material is not intended for photorealism. It's useful for helping OSM Buildings read more as buildings in a scene, but it's not perfect. 
The window pattern is projected in world space along the X and Y axes. Therefore, it's subject to all the drawbacks of a world-aligned texture. 
Here's how it looks in various situations on various buildings. 

- The material can't know where the ground is, so each story of a building is aligned at the same Z height. Windows may appear to clip through the ground. ![image](https://user-images.githubusercontent.com/39537389/207663711-4b8f71e1-3136-4a06-8265-c54c0fcc3e5b.png)
- The material is applied to all objects in the tileset, whether or not they're supposed to represent a building. For example, these are bridge towers. ![image](https://user-images.githubusercontent.com/39537389/207664771-333e505e-1561-4f79-8bee-0cbcc0e110b6.png)
- Since it's world-aligned, if you are far from the origin the windows will no longer be applied correctly. You can fix this with origin rebasing. ![image](https://user-images.githubusercontent.com/39537389/207666124-f6da50c1-08fa-4bfc-8bb8-9f053fe0a870.png)
- The horizontal width of the windows will vary and possibly overlap depending on the building's alignment to the cardinal directions. 
![image](https://user-images.githubusercontent.com/39537389/207666736-6afb61fd-1453-4117-9599-7ad752f8b04c.png)

**Comment by j9liu** [comment]
Seems like this was addressed by #37, so I'm going to close this issue. Thanks @argallegos !
