### ISSUE TITLE
how to transparent the skirt when make the terrain transparent ?

### ISSUE THREAD

**Issue by VegetableWithChicken** [CesiumGS/cesium-unreal-samples#40]
When I make the terrain transparent, a skirt will appear, how can I transparent this skirt?

**Comment by kring** [comment]
Please post questions like these to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10). We use GitHub issues exclusively for bug reports and feature requests.

There's currently no way to hide the skirts. Your best bet for the time being is probably to build Cesium for Unreal yourself, and modify cesium-native to avoid adding the skirts in the first place. Skirts are added here:
https://github.com/CesiumGS/cesium-native/blob/cfd1facb1a11c3ce3f79ef7d5e0b887d003e1d68/Cesium3DTilesSelection/src/QuantizedMeshLoader.cpp#L838

**Comment by VegetableWithChicken** [comment]
您好，我一般不常用邮箱，有重要邮件，请QQ我下，谢谢!

**Comment by VegetableWithChicken** [comment]
![image](https://user-images.githubusercontent.com/56669924/231052683-cd9f04b3-2f5a-4b4f-be12-f8cc04e01ba1.png)

#### qa:
I did, but why does the skirt hide one part, but the other part has a golden frame?

**Comment by VegetableWithChicken** [comment]
> ![image](https://user-images.githubusercontent.com/56669924/231052683-cd9f04b3-2f5a-4b4f-be12-f8cc04e01ba1.png)
> 
> #### qa:
> I did, but why does the skirt hide one part, but the other part has a golden frame?

@kring
